Cheffi-Git/Cheffi-Server

src/main/java/com/cheffi/common/constant/Address.java, src/main/java/com/cheffi/common/constant/DetailedAddress.java
common.constant 폴더에 @Embeddable 클래스 2개 추가
=> Feat: add Address, DetailAddress

src/main/java/com/cheffi/common/constant/Address.java, src/main/java/com/cheffi/common/constant/DetailedAddress.java
Add two embedded types:
* Address
* DetailedAdress(child of Address)
=> Feat: add embedded types

.github/workflows/deploy_dev.yml
resolved #9 
- dev 서버 `~/workspace/cheffi_server_dev`경로에 `DockerFile`, `.jar`을 복사해서 docker run 하는 구조 입니다.
- secrets의 경우 해당 repo권한이 없어서 추가해 주시면 제가 넣어둘게요.
=> feat: add github action YAML to deploy to environment

src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/common/config/exception/GlobalExceptionHandler.java, src/main/java/com/cheffi/common/config/exception/business/AuthenticationException.java, src/main/java/com/cheffi/common/config/exception/business/BusinessException.java, src/main/java/com/cheffi/common/config/exception/business/EntityNotFoundException.java, src/main/java/com/cheffi/common/response/ErrorResponse.java
서버 애플리케이션의 에러 처리를 공통적으로 처리할 `GlobalExceptionHandler`과 비지니스 로직의 예외를 나타내는 `BusinessException`와 그것의 자식 클래스들을 추가했습니다.
=> Feat: add `GlobalExceptionHandler`, `BusinessException` and subclasses

src/main/java/com/cheffi/common/config/review/domain/Food.java, src/main/java/com/cheffi/common/config/review/domain/Rating.java, src/main/java/com/cheffi/common/config/review/domain/Restuarant.java, src/main/java/com/cheffi/common/config/review/domain/Review.java, src/main/java/com/cheffi/common/config/review/domain/ReviewPhoto.java, src/main/java/com/cheffi/common/config/review/domain/ReviewTag.java, src/main/java/com/cheffi/common/config/tag/Tag.java, src/main/java/com/cheffi/common/constant/Address.java
add Review, ReviewPhoto, Food, Review Tag
=> Feat: add entities belonging to review

src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/domain/CheffiCoin.java, src/main/java/com/cheffi/avatar/domain/Follow.java, src/main/java/com/cheffi/avatar/domain/Inquiry.java, src/main/java/com/cheffi/avatar/domain/Notification.java, src/main/java/com/cheffi/avatar/domain/Point.java, src/main/java/com/cheffi/common/config/jpa/AuditorAwareImpl.java, src/main/java/com/cheffi/common/config/jpa/JpaConfig.java, src/main/java/com/cheffi/common/constant/Address.java, src/main/java/com/cheffi/common/domain/BaseEntity.java, src/main/java/com/cheffi/common/domain/BaseTimeEntity.java, src/main/java/com/cheffi/notice/domain/Notice.java, src/main/java/com/cheffi/review/domain/Food.java, src/main/java/com/cheffi/review/domain/Rating.java, src/main/java/com/cheffi/review/domain/Restaurant.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/domain/ReviewPhoto.java, src/main/java/com/cheffi/review/domain/ReviewTag.java, src/main/java/com/cheffi/user/domain/Bookmark.java, src/main/java/com/cheffi/user/domain/BuyItem.java, src/main/java/com/cheffi/user/domain/User.java, src/main/java/com/cheffi/user/domain/UserRole.java
=> Feat: add globally used entity

src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/domain/CheffiCoin.java, src/main/java/com/cheffi/avatar/domain/Follow.java, src/main/java/com/cheffi/avatar/domain/Inquiry.java, src/main/java/com/cheffi/avatar/domain/Notification.java, src/main/java/com/cheffi/avatar/domain/Point.java, src/main/java/com/cheffi/avatar/domain/UserTag.java, src/main/java/com/cheffi/common/config/jpa/AuditorAwareImpl.java, src/main/java/com/cheffi/common/config/jpa/JpaConfig.java, src/main/java/com/cheffi/common/constant/Address.java, src/main/java/com/cheffi/common/domain/BaseEntity.java, src/main/java/com/cheffi/common/domain/BaseTimeEntity.java, src/main/java/com/cheffi/notice/domain/Notice.java, src/main/java/com/cheffi/review/domain/Food.java, src/main/java/com/cheffi/review/domain/Rating.java, src/main/java/com/cheffi/review/domain/Restaurant.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/domain/ReviewPhoto.java, src/main/java/com/cheffi/review/domain/ReviewTag.java, src/main/java/com/cheffi/user/domain/Bookmark.java, src/main/java/com/cheffi/user/domain/BuyItem.java, src/main/java/com/cheffi/user/domain/User.java, src/main/java/com/cheffi/user/domain/UserRole.java
=> Feat: add `UserTag`

src/main/java/com/cheffi/common/config/web/WebConfig.java, src/main/java/com/cheffi/common/response/ApiResponse.java, src/main/java/com/cheffi/test/TestController.java
- add common format for response, `ApiResponse`
- add CORS setting class 
Related to #14
=> Feat: add common configuration

build.gradle, src/main/resources/application.yml
Feat: add QueryDSL, change JPA settings
Related to #14
=> Feat: add QueryDSL, change JPA settings

src/main/java/com/cheffi/health/controller/HealthCheckController.java, src/main/java/com/cheffi/health/dto/HealthCheckResponse.java
Feat: add `HealthCheckController`
Related to #14
=> Feat: add `HealthCheckController`

src/main/java/com/cheffi/avatar/domain/UserTag.java, src/main/java/com/cheffi/common/domain/BaseTimeEntity.java, src/main/java/com/cheffi/user/controller/UserController.java, src/main/java/com/cheffi/user/dto/UserInfoDto.java, src/main/java/com/cheffi/user/service/UserService.java, src/main/resources/application.yml
- `GET /users`: querying user's information
- `POST /users/tags`: change user's tastes tags
Related to #23
=> Feat: add Mock APIs about `User`

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/domain/UserTag.java, src/main/java/com/cheffi/avatar/dto/TagsChangeRequest.java, src/main/java/com/cheffi/avatar/dto/TagsChangeResponse.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/common/domain/BaseTimeEntity.java, src/main/java/com/cheffi/common/response/ApiResponse.java, src/main/java/com/cheffi/user/controller/UserController.java, src/main/java/com/cheffi/user/dto/UserInfoDto.java, src/main/java/com/cheffi/user/service/UserService.java, src/main/resources/application.yml
=> Feat: add Mock APIs about `Avatar`

src/main/java/com/cheffi/common/config/swagger/SwaggerConfig.java, src/main/java/com/cheffi/review/ReviewService.java, src/main/java/com/cheffi/review/constant/RatingType.java, src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/review/domain/Restaurant.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/dto/RatingInfoDto.java, src/main/java/com/cheffi/review/dto/RestaurantInfoDto.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/dto/ReviewPhotoInfoDto.java, src/main/java/com/cheffi/review/dto/request/RegisterReviewRequest.java, src/main/java/com/cheffi/review/dto/request/SearchReviewRequest.java, src/main/java/com/cheffi/review/dto/request/WriteReviewRequest.java, src/main/java/com/cheffi/review/dto/response/SearchReviewResponse.java
#25  변경내역 한번에 보이도록 새로운 PR로 옮겼습니다.
=> Feat: add searhReview, serarchReviews API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/dto/common/TagDto.java, src/main/java/com/cheffi/avatar/dto/request/TagsChangeRequest.java, src/main/java/com/cheffi/avatar/dto/response/AvatarInfoResponse.java, src/main/java/com/cheffi/avatar/dto/response/SelfAvatarInfoResponse.java, src/main/java/com/cheffi/avatar/dto/response/TagsChangeResponse.java, src/main/java/com/cheffi/avatar/service/AvatarService.java
=> Feat: add Mock APIs about `Avatar` - 2

src/main/java/com/cheffi/tag/controller/TagController.java, src/main/java/com/cheffi/tag/service/TagService.java
- API querying all tags
Related to #23
=> Feat: add `GET /tags` Mock API

.github/workflows/CD-ec2.yml
주현님 서버에 배포전까지 사용하는 CD workflow입니다.
develop branch에 PR트리거 발생시 배포됩니다.
http://43.202.121.135:8080/swagger-ui/index.html
=> Add CD-ec2.yml

Dockerfile, Dockerfile-helper, build.gradle, docker-compose-helper.yml, docker-compose.yml, src/main/java/com/cheffi/common/config/security/SecurityConfig.java, src/main/resources/application-dev.yml
=> Feat: add Dockerfile & docker-compose for deploying

Dockerfile, Dockerfile-helper, build.gradle, docker-compose-helper.yml, docker-compose.yml, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/common/config/exception/business/EntityNotFoundException.java, src/main/java/com/cheffi/common/config/security/SecurityConfig.java, src/main/java/com/cheffi/oauth/dto/SocialUserCreateRequest.java, src/main/java/com/cheffi/user/constant/Password.java, src/main/java/com/cheffi/user/constant/UserType.java, src/main/java/com/cheffi/user/domain/User.java, src/main/java/com/cheffi/user/domain/UserRole.java, src/main/java/com/cheffi/user/dto/UserCreateRequest.java, src/main/java/com/cheffi/user/dto/UserInfoDto.java, src/main/java/com/cheffi/user/repository/UserRepository.java, src/main/java/com/cheffi/user/service/UserService.java, src/main/resources/application-dev.yml, src/test/java/com/cheffi/user/domain/UserTest.java
- set `Redis` and `Spring Session` Configuration
- add logic registering `User` for `OAuth Login` API
Related to #42
=> Feat: add logic of register `User`

.github/workflows/deploy_dev_ec2.yml
- divide a job into two jobs, `build` and `deploy`
- test when build
- add command to remove dangling images
Related to #9
=> Feat: change GitHun Actions script

.github/workflows/deploy_dev_ec2.yml
Fix deployment error
check the details on #55 
Related to #9
=> Hotfix: fix deployment error

.github/workflows/deploy_dev_ec2.yml, .gitignore, build.gradle, src/main/java/com/cheffi/common/config/s3/AwsConfig.java, src/main/java/com/cheffi/common/service/FileUploadService.java, src/main/java/com/cheffi/test/TestController.java, src/main/resources/application.yml
- add S3 configuration
- add `POST /test/upload` API for testing file upload to AWS S3 bucket
Related to #14
=> Feat: add S3 configuration

.github/workflows/test_action.yml, src/test/java/com/cheffi/avatar/domain/AvatarTest.java
- fix test compile error and fails
- automate test when pull request
=> Hotfix: fix test compile error and fails

src/main/java/com/cheffi/common/config/web/WebConfig.java
=> Feat: expose header `Authorization` on web browser

build.gradle, src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/domain/Bookmark.java, src/main/java/com/cheffi/avatar/domain/BuyItem.java, src/main/java/com/cheffi/avatar/domain/ProfilePhoto.java, src/main/java/com/cheffi/common/aspect/SessionUpdateAspect.java, src/main/java/com/cheffi/common/aspect/TimeTraceAspect.java, src/main/java/com/cheffi/common/aspect/annotation/UpdatePrincipal.java, src/main/java/com/cheffi/common/service/SecurityContextService.java, src/main/java/com/cheffi/oauth/controller/OAuthController.java, src/main/java/com/cheffi/oauth/model/UserPrincipal.java, src/main/java/com/cheffi/oauth/service/OAuthService.java, src/main/java/com/cheffi/review/domain/ReviewPhoto.java, src/main/java/com/cheffi/test/TestController.java, src/test/java/com/cheffi/avatar/domain/AvatarTest.java
=> Feat: set configurations for Sign Up

src/main/java/com/cheffi/common/aspect/TimeTraceAspect.java, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/common/constant/S3RootPath.java, src/main/java/com/cheffi/common/dto/ImageFileInfo.java, src/main/java/com/cheffi/common/dto/ImageSize.java, src/main/java/com/cheffi/common/service/FileUploadService.java, src/main/java/com/cheffi/common/service/ImagePathStrategy.java, src/main/java/com/cheffi/test/TestController.java, src/main/resources/application.yml, src/test/java/com/cheffi/common/service/ImagePathStrategyTest.java
=> Feat: add uploading image logic and test API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/repository/AvatarRepository.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/common/aspect/SessionUpdateAspect.java, src/main/java/com/cheffi/oauth/model/UserPrincipal.java, src/main/java/com/cheffi/oauth/service/OAuthService.java, src/main/java/com/cheffi/user/controller/UserController.java, src/main/java/com/cheffi/user/domain/User.java, src/main/java/com/cheffi/user/dto/adapter/UserInfo.java, src/main/java/com/cheffi/user/dto/request/ChangeTermsAgreementRequest.java, src/main/java/com/cheffi/user/repository/UserRepository.java, src/main/java/com/cheffi/user/service/UserService.java, src/test/java/com/cheffi/avatar/domain/AvatarTest.java
=> Feat: add API to change `User`'s acceptance of terms

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/domain/ProfilePhoto.java, src/main/java/com/cheffi/avatar/dto/request/ChangeProfilePhotoRequest.java, src/main/java/com/cheffi/avatar/repository/ProfilePhotoRepository.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/avatar/service/ProfilePhotoService.java, src/main/java/com/cheffi/common/dto/ImageFileInfo.java, src/main/java/com/cheffi/common/service/FileUploadService.java, src/main/java/com/cheffi/review/domain/ReviewPhoto.java, src/main/java/com/cheffi/user/dto/adapter/UserInfo.java
=> Feat: add `POST /avatar/photos` API

.github/workflows/deploy_dev_ec2.yml, .github/workflows/test_action.yml
=> Feat: add Steps to notify with `Slack`

src/main/java/com/cheffi/avatar/dto/common/TagDto.java, src/main/java/com/cheffi/common/dev/SetupDataLoader.java, src/main/java/com/cheffi/tag/controller/TagController.java, src/main/java/com/cheffi/tag/domain/Tag.java, src/main/java/com/cheffi/tag/repository/TagRepository.java, src/main/java/com/cheffi/tag/service/TagService.java
- add `GET /tags` API
- add SetupDataLoader
=> Feat: add `GET /tags` API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/controller/AvatarTagController.java, src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/domain/AvatarTag.java, src/main/java/com/cheffi/avatar/dto/common/TagDto.java, src/main/java/com/cheffi/avatar/dto/request/TagsChangeRequest.java, src/main/java/com/cheffi/avatar/dto/response/TagsChangeResponse.java, src/main/java/com/cheffi/avatar/repository/AvatarRepository.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/avatar/service/AvatarTagService.java, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/common/dev/SetupDataLoader.java, src/main/java/com/cheffi/tag/configuration/TagValidationConfiguration.java, src/main/java/com/cheffi/tag/service/TagService.java, src/main/java/com/cheffi/tag/service/validation/MapValidationPolicy.java, src/main/java/com/cheffi/tag/service/validation/SimpleValidationPolicy.java, src/main/java/com/cheffi/tag/service/validation/TagValidationPolicy.java, src/test/java/com/cheffi/avatar/domain/AvatarTest.java, src/test/java/com/cheffi/tag/service/TagServiceTest.java, src/test/java/com/cheffi/tag/service/validation/MapValidationPolicyTest.java, src/test/java/com/cheffi/tag/service/validation/SimpleValidationPolicyTest.java, src/test/java/com/cheffi/tag/service/validation/TagValidationPolicyTest.java, src/test/java/com/cheffi/user/domain/UserTest.java
=> Feat: add OneToMany relation to `Avatar` with `AvatarTag`

src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/repository/AvatarRepository.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/user/controller/UserController.java, src/main/java/com/cheffi/user/domain/User.java, src/main/java/com/cheffi/user/service/ProfileService.java, src/main/java/com/cheffi/user/service/UserService.java, src/test/java/com/cheffi/avatar/domain/AvatarTest.java, src/test/java/com/cheffi/user/domain/UserTest.java
=> Feat: add `POST /users/profile` API

src/main/java/com/cheffi/avatar/controller/AvatarController.java
=> Feta: add `GET /avatars/nickname/inuse` API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/controller/AvatarTagController.java, src/main/java/com/cheffi/oauth/controller/OAuthController.java, src/main/java/com/cheffi/oauth/dto/response/OidcLoginResponse.java, src/main/java/com/cheffi/oauth/service/OAuthService.java, src/main/java/com/cheffi/user/controller/UserController.java
=> Feat: add features when signing in

src/main/java/com/cheffi/common/response/ApiPageResponse.java
=> Feta: add `ApiPageResponse`

Dockerfile, docker-compose.yml, src/main/resources/application-dev.yml
Feat: change port of development server 8080 to 80
=> Feat: change port of development server 8080 to 80

src/main/java/com/cheffi/user/domain/User.java
- change Table name of `User` (`users` to `user`)
=> Feat: change Table name of `User` `users` to user

src/main/java/com/cheffi/common/constant/DetailedAddress.java, src/main/java/com/cheffi/review/constant/RestaurantStatus.java, src/main/java/com/cheffi/review/controller/RestaurantController.java, src/main/java/com/cheffi/review/domain/Restaurant.java, src/main/java/com/cheffi/review/domain/RestaurantData.java, src/main/java/com/cheffi/review/domain/RestaurantInfo.java, src/main/java/com/cheffi/review/dto/RestaurantInfoDto.java, src/main/java/com/cheffi/review/repository/RestaurantDataRepository.java, src/main/java/com/cheffi/review/repository/RestaurantRepository.java, src/main/java/com/cheffi/review/service/RestaurantDataService.java, src/main/java/com/cheffi/review/service/RestaurantInfoService.java, src/main/java/com/cheffi/review/service/ReviewCudService.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/test/java/com/cheffi/common/constant/DetailedAddressTest.java, src/test/java/com/cheffi/review/domain/RestaurantTest.java, src/test/java/com/cheffi/review/service/RestaurantInfoServiceTest.java, src/test/java/com/cheffi/review/service/RestaurantServiceTest.java
=> Feat: add new features to `GET /restaurants` API

src/main/java/com/cheffi/review/constant/RestaurantStatus.java, src/main/java/com/cheffi/review/domain/Restaurant.java, src/main/java/com/cheffi/review/domain/RestaurantData.java, src/test/java/com/cheffi/review/domain/RestaurantTest.java
=> Hotfix: fix `RestaurantStatus` from ORDINAL to STRING

src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/domain/CheffiCoin.java, src/main/java/com/cheffi/avatar/repository/CheffiCoinRepository.java, src/main/java/com/cheffi/avatar/service/CheffiCoinService.java, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/oauth/dto/response/OidcLoginResponse.java, src/main/java/com/cheffi/oauth/service/OAuthService.java, src/main/java/com/cheffi/review/service/ReviewService.java, src/main/java/com/cheffi/user/domain/User.java, src/test/java/com/cheffi/user/domain/UserTest.java
잠긴 게시글을 읽을 때 코인을 1개 소비하고
매일 첫 로그인 시 코인을 5개 획득하는 로직을 추가했습니다.
Related to #81
=> Feat: add logic using / consuming `CheffiCoin`

src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/review/domain/Bookmark.java, src/main/java/com/cheffi/review/repository/BookmarkRepository.java, src/main/java/com/cheffi/review/service/BookmarkService.java
=> Feat: add logics about `Bookmark`

src/main/java/com/cheffi/review/domain/Rating.java, src/main/java/com/cheffi/review/dto/RatingInfoDto.java, src/main/java/com/cheffi/review/repository/RatingRepository.java, src/main/java/com/cheffi/review/service/RatingService.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/test/java/com/cheffi/review/service/RatingServiceTest.java
=> Feat: add logics to get information of `Rating`

src/main/java/com/cheffi/oauth/dto/response/OidcLoginResponse.java
=> Hotfix: fix dto schema

src/main/java/com/cheffi/tag/repository/TagRepository.java, src/main/java/com/cheffi/tag/service/TagMatchService.java, src/main/java/com/cheffi/tag/service/TagService.java
=> Feat: add logics to calculate number of matched tags

src/main/java/com/cheffi/review/controller/RestaurantController.java
`GET /restaurants` API에서
아직 지원되지 않는 쿼리 파라미터(city, province)로 인해 버그가 발생해 수정하는 코드입니다.
=> Fix: remove unused query parameters

src/main/java/com/cheffi/oauth/dto/response/OidcLoginResponse.java, src/main/java/com/cheffi/review/dto/response/ReviewWriterInfoDto.java
JSON에서 프로퍼티명을 공통적으로 변경하기 위한 필드명 수정입니다.
=> Feat: refactor json property name of DTOs

src/main/java/com/cheffi/review/domain/ViewHistory.java, src/main/java/com/cheffi/review/repository/ViewHistoryRepository.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ViewHistoryService.java
Feat: add logic of insert view history when viewing one review 
Related to #81
=> Feat: add logic of insert view history

build.gradle, src/main/java/com/cheffi/common/constant/Address.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/domain/ReviewRanking.java, src/main/java/com/cheffi/review/dto/ReviewTypedTuple.java, src/main/java/com/cheffi/review/dto/dao/ScoreDto.java, src/main/java/com/cheffi/review/repository/RatingJpaRepository.java, src/main/java/com/cheffi/review/repository/ReviewRepository.java, src/main/java/com/cheffi/review/repository/ViewHistoryJpaRepository.java, src/main/java/com/cheffi/review/service/RatingService.java, src/main/java/com/cheffi/review/service/ReviewRankingService.java, src/main/java/com/cheffi/review/service/ReviewService.java, src/main/java/com/cheffi/review/service/ViewHistoryService.java, src/main/resources/application-local.yml
=> Feat: add logic of calculate review ranking of certain area

src/main/java/com/cheffi/common/dto/CursorPage.java, src/main/java/com/cheffi/common/response/ApiCursorPageResponse.java, src/main/java/com/cheffi/region/controller/RegionController.java
Add common format class for response of cursor pagination
=> Feat: add `ApiCursorPageResponse`

src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/common/config/redis/RedisConfig.java, src/main/java/com/cheffi/common/constant/Address.java, src/main/java/com/cheffi/common/dto/CursorPage.java, src/main/java/com/cheffi/common/response/ApiCursorPageResponse.java, src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/dto/ReviewPhotoInfoDto.java, src/main/java/com/cheffi/review/dto/ReviewTypedTuple.java, src/main/java/com/cheffi/review/dto/request/AreaSearchRequest.java, src/main/java/com/cheffi/review/helper/ReviewRedisKeyGenerator.java, src/main/java/com/cheffi/review/helper/ReviewSearchPeriodStrategy.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/repository/ReviewRedisRepository.java, src/main/java/com/cheffi/review/service/ReviewRankingService.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java, src/main/java/com/cheffi/review/service/ReviewTrendingService.java, src/main/java/com/cheffi/util/constant/SearchConstant.java, src/main/java/com/cheffi/util/model/ExactPeriod.java
=> Feat: add `GET /reviews/areas` API

src/main/java/com/cheffi/review/service/ReviewRankingService.java, src/main/java/com/cheffi/review/service/ReviewService.java, src/main/java/com/cheffi/review/service/ReviewTrendingService.java
return empty data if no review in specific area instead throwing error message
=> Refactor: return empty data if no review in specific area

src/main/java/com/cheffi/common/config/jpa/AuditorAwareImpl.java, src/main/java/com/cheffi/common/dto/CursorPage.java, src/main/java/com/cheffi/common/response/ApiCursorPageResponse.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/dto/request/AreaSearchRequest.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewTrendingService.java
=> Feat: add additional info about review to response

src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/common/dto/RedisZSetRequest.java, src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/review/domain/ReviewRanking.java, src/main/java/com/cheffi/review/dto/ReviewSearchCondition.java, src/main/java/com/cheffi/review/dto/ReviewTuple.java, src/main/java/com/cheffi/review/dto/ReviewTuples.java, src/main/java/com/cheffi/review/dto/request/AreaTagSearchRequest.java, src/main/java/com/cheffi/review/helper/ReviewRedisKeyGenerator.java, src/main/java/com/cheffi/review/helper/ReviewSearchPeriodStrategy.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/repository/ReviewRedisRepository.java, src/main/java/com/cheffi/review/repository/ReviewRepository.java, src/main/java/com/cheffi/review/service/ReviewRankingService.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java, src/main/java/com/cheffi/review/service/ReviewTrendingService.java, src/main/java/com/cheffi/tag/service/TagService.java, src/main/java/com/cheffi/util/model/ExactPeriod.java
=> Feat: add `GET /reviews/areas/tags` API

src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/review/dto/MenuSearchRequest.java, src/main/java/com/cheffi/review/dto/ReviewCursor.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java
=> Feat: add `GET /reviews/menus` API

src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/avatar/service/FollowService.java
- 팔로우 추가 및 취소 시
아바타에 팔로우 및 팔로잉 수 컬럼 업데이트 하는 로직 추가
=> Feat: add logics to update count of follower and following

src/main/java/com/cheffi/avatar/domain/Avatar.java, src/main/java/com/cheffi/review/service/ReviewCudService.java
=> Feat: add logics to update count of post

src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/avatar/dto/common/TagDto.java, src/main/java/com/cheffi/avatar/dto/response/RecommendFollowResponse.java, src/main/java/com/cheffi/avatar/repository/FollowJpaRepository.java, src/main/java/com/cheffi/avatar/service/FollowService.java, src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
=> Feat: add `GET /avatars/follow/recommend/tags` API

src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/review/dto/AddressSearchRequest.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java
=> Feat: add `GET /reviews/address` API

src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/avatar/dto/FollowCursor.java, src/main/java/com/cheffi/avatar/dto/GetFollowRequest.java, src/main/java/com/cheffi/avatar/dto/response/GetFollowResponse.java, src/main/java/com/cheffi/avatar/repository/FollowJpaRepository.java, src/main/java/com/cheffi/avatar/service/FollowService.java
=> Feat: add `GET /follows/following`API

src/main/java/com/cheffi/review/controller/RatingController.java, src/main/java/com/cheffi/review/domain/Rating.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/dto/request/PutRatingRequest.java, src/main/java/com/cheffi/review/repository/RatingRepository.java, src/main/java/com/cheffi/review/service/RatingService.java
=> Feat: add `PUT /reviews/rate` API

src/main/java/com/cheffi/review/controller/BookmarkController.java
URI 수정 
기존: /bookmarks
수정: /api/v1/bookmarks
=> Fix: change URI of `BookmarkController`

src/main/java/com/cheffi/avatar/dto/MyPageInfo.java, src/main/java/com/cheffi/avatar/dto/adapter/SelfAvatarInfo.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/review/controller/MyPageController.java
=> Feat: add `GET /my-page` API

src/main/java/com/cheffi/review/controller/MyPageController.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/dto/request/GetMyPageReviewRequest.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/repository/querydsl/ReviewQueryProcessor.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java
=> Feat: add `GET /my-page/{id}/reviews` API

src/main/java/com/cheffi/review/constant/RatingType.java, src/main/java/com/cheffi/review/controller/RatingController.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/dto/RatingInfoDto.java, src/main/java/com/cheffi/review/dto/response/GetReviewResponse.java, src/test/java/com/cheffi/review/service/RatingServiceTest.java
=> Feat: add feature to cancel rating to `PUT /reviews/rate` API

src/main/java/com/cheffi/review/controller/MyPageController.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/repository/querydsl/ReviewQueryProcessor.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java
=> Feat: add `GET /my-page/{id}/bookmarks` API

src/main/java/com/cheffi/review/controller/MyPageController.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/repository/querydsl/ReviewQueryProcessor.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ReviewService.java
=> Feat: add `GET /my-page/{id}/purchase` API

src/main/java/com/cheffi/avatar/controller/FollowController.java
=> Feat: add `GET /follows/{id}/follower` API

src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/dto/request/DeleteReviewRequest.java, src/main/java/com/cheffi/review/dto/request/UpdateReviewRequest.java, src/main/java/com/cheffi/review/service/ReviewCudService.java
=> Feat: add `DELETE /reviews` API

src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/cs/constant/ReportReason.java, src/main/java/com/cheffi/cs/controller/ReportController.java, src/main/java/com/cheffi/cs/domain/Report.java, src/main/java/com/cheffi/cs/dto/PostReportRequest.java, src/main/java/com/cheffi/cs/repository/ReportRepository.java, src/main/java/com/cheffi/cs/service/ReportService.java
=> Feat: add `POST /reports` API

src/main/java/com/cheffi/avatar/repository/FollowRepository.java, src/main/java/com/cheffi/avatar/service/FollowService.java, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/cs/controller/BlockController.java, src/main/java/com/cheffi/cs/domain/Block.java, src/main/java/com/cheffi/cs/dto/PostBlockRequest.java, src/main/java/com/cheffi/cs/dto/PostReportRequest.java, src/main/java/com/cheffi/cs/repository/BlockRepository.java, src/main/java/com/cheffi/cs/service/BlockService.java, src/test/java/com/cheffi/avatar/domain/FollowTest.java, src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
- 차단 시 모든 팔로우 관계 취소
- `FollowRepository.existsBySubjectAndTarget()` 의 매개변수와 쿼리 변경
Related to #152
=> Feat: add `POST /blocks` API

src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/cs/controller/BlockController.java, src/main/java/com/cheffi/cs/dto/DeleteBlockRequest.java, src/main/java/com/cheffi/cs/repository/BlockRepository.java, src/main/java/com/cheffi/cs/service/BlockService.java
=> Feat: add `DELETE /blocks` API

src/main/java/com/cheffi/cs/controller/BlockController.java, src/main/java/com/cheffi/cs/dto/GetBlockRequest.java, src/main/java/com/cheffi/cs/dto/GetBlockResponse.java, src/main/java/com/cheffi/cs/repository/BlockJpaRepository.java, src/main/java/com/cheffi/cs/service/BlockService.java
=> Feat: add `GET /blocks` API

src/main/java/com/cheffi/notification/constant/NotificationCategory.java, src/main/java/com/cheffi/notification/controller/NotificationController.java, src/main/java/com/cheffi/notification/domain/Notification.java, src/main/java/com/cheffi/notification/dto/GetNotificationRequest.java, src/main/java/com/cheffi/notification/dto/NotificationDto.java, src/main/java/com/cheffi/notification/repository/NotificationJpaRepository.java, src/main/java/com/cheffi/notification/service/NotificationService.java
- 조회시 자동 확인 처리
- 추후 벌크 업데이트로 변경 필요
=> Feat: add `GET /notifications` API

src/main/java/com/cheffi/notification/controller/NotificationController.java, src/main/java/com/cheffi/notification/dto/DeleteNotificationRequest.java, src/main/java/com/cheffi/notification/repository/NotificationRepository.java, src/main/java/com/cheffi/notification/service/NotificationService.java
=> Feat: add `DELETE /notifications` API

src/main/java/com/cheffi/notification/controller/NotificationController.java, src/main/java/com/cheffi/notification/repository/NotificationRepository.java, src/main/java/com/cheffi/notification/service/NotificationService.java
사용자가 아직 확인하지 않은 알림이 있는지 조회하는 API 추가 (메인화면)
=> Feat: add `GET /notifications/unchecked` API

src/main/java/com/cheffi/avatar/repository/AvatarJpaRepository.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/common/code/ErrorCode.java, src/main/java/com/cheffi/cs/service/BlockService.java, src/main/java/com/cheffi/profile/controller/ProfileController.java, src/main/java/com/cheffi/profile/dto/ProfileInfo.java, src/main/java/com/cheffi/profile/service/ProfileService.java, src/main/java/com/cheffi/user/controller/UserController.java, src/main/java/com/cheffi/user/service/SignUpProfileService.java, src/test/java/com/cheffi/avatar/service/FollowServiceTest.java
- add `GET profile/{id}` API
- change name of `user.service.ProfileService` to `user.service.SignUpProfileService`
Related to #142
=> Feat: add `GET profile/{id}` API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/controller/AvatarTagController.java, src/main/java/com/cheffi/avatar/controller/CfcController.java, src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/cs/controller/BlockController.java, src/main/java/com/cheffi/cs/controller/ReportController.java, src/main/java/com/cheffi/notification/controller/NotificationController.java, src/main/java/com/cheffi/oauth/controller/OAuthController.java, src/main/java/com/cheffi/profile/controller/ProfileController.java, src/main/java/com/cheffi/region/controller/RegionController.java, src/main/java/com/cheffi/review/constant/ReviewStatus.java, src/main/java/com/cheffi/review/controller/BookmarkController.java, src/main/java/com/cheffi/review/controller/RatingController.java, src/main/java/com/cheffi/review/controller/RestaurantController.java, src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/tag/controller/TagController.java, src/main/java/com/cheffi/user/controller/UserController.java, src/main/resources/application-swagger.yml, src/main/resources/application.yml
스웨거 화면별로 태그 구성 (가독성 향상을 위해)
Docs: Restructuring Swagger Documents
=> Docs: Restructuring Swagger Documents

src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/avatar/repository/FollowJpaRepository.java, src/main/java/com/cheffi/avatar/repository/FollowRepository.java, src/main/java/com/cheffi/avatar/service/FollowService.java, src/main/java/com/cheffi/common/async/AsyncConfig.java, src/main/java/com/cheffi/event/event/ReviewCreateEvent.java, src/main/java/com/cheffi/event/listener/NotificationEventListener.java, src/main/java/com/cheffi/notification/constant/NotificationCategory.java, src/main/java/com/cheffi/notification/domain/Notification.java, src/main/java/com/cheffi/notification/repository/NotificationJdbcRepository.java, src/main/java/com/cheffi/notification/repository/NotificationJpaRepository.java, src/main/java/com/cheffi/notification/repository/NotificationRepository.java, src/main/java/com/cheffi/notification/service/NotificationService.java, src/main/java/com/cheffi/review/service/ReviewCudService.java
- add `AsyncConfig`, use `ThreadPoolTaskExecutor` for async task
- use JDBC bulk insert for performant data inserts
=> Feat: send notifications to followers as review is created

src/main/java/com/cheffi/avatar/repository/AvatarRepository.java, src/main/java/com/cheffi/avatar/service/AvatarService.java, src/main/java/com/cheffi/common/auth/Authorities.java, src/main/java/com/cheffi/common/service/SecurityContextService.java, src/main/java/com/cheffi/event/event/ReviewCreateEvent.java, src/main/java/com/cheffi/event/listener/NotificationEventListener.java, src/main/java/com/cheffi/notification/domain/Notification.java, src/main/java/com/cheffi/notification/service/NotificationService.java, src/main/java/com/cheffi/oauth/model/AuthenticationToken.java, src/main/java/com/cheffi/oauth/model/UserPrincipal.java, src/main/java/com/cheffi/oauth/service/OAuthService.java, src/main/java/com/cheffi/review/service/ReviewCudService.java
- use JDBC bulk insert for performant data inserts
- small changes with `UserPrincipal`
=> Feat: send notifications to all active users as official review is created

src/main/java/com/cheffi/user/controller/UserController.java, src/main/java/com/cheffi/user/dto/request/ChangeTermsAgreementRequest.java
=> Feat: remove `analysisAgreed` field

src/main/java/com/cheffi/cs/constant/QnaCategory.java, src/main/java/com/cheffi/cs/controller/QnaController.java, src/main/java/com/cheffi/cs/domain/Qna.java, src/main/java/com/cheffi/cs/dto/QnaDto.java, src/main/java/com/cheffi/cs/repository/QnaJpaRepository.java, src/main/java/com/cheffi/cs/service/QnaService.java, src/main/resources/application-swagger.yml
- add `Qna` Entity
- add API of query `Qna`
Related:
- #152
=> Feat: add `GET /qna` API

src/main/java/com/cheffi/notice/controller/NoticeController.java, src/main/java/com/cheffi/notice/domain/Notice.java, src/main/java/com/cheffi/notice/dto/NoticeDto.java, src/main/java/com/cheffi/notice/repository/NoticeRepository.java, src/main/java/com/cheffi/notice/service/NoticeService.java, src/main/resources/application-swagger.yml
- add API of paging `Notice`
Related:
- #152
=> Feat: add `GET /notice` API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/controller/AvatarTagController.java, src/main/java/com/cheffi/avatar/controller/CfcController.java, src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/notice/controller/NoticeController.java, src/main/java/com/cheffi/notification/controller/NotificationController.java, src/main/java/com/cheffi/oauth/controller/OAuthController.java, src/main/java/com/cheffi/profile/controller/ProfileController.java, src/main/java/com/cheffi/review/controller/BookmarkController.java, src/main/java/com/cheffi/review/controller/RestaurantController.java, src/main/java/com/cheffi/review/controller/ReviewController.java, src/main/java/com/cheffi/user/controller/UserController.java
=> Docs: indicate whether authentication is required

src/main/java/com/cheffi/cs/constant/ReportReason.java, src/main/java/com/cheffi/cs/controller/ReportController.java, src/main/java/com/cheffi/cs/dto/GetReportReasonResponse.java, src/main/java/com/cheffi/cs/service/ReportService.java
=> Feat: add `GET /reports/reasons` API

src/main/java/com/cheffi/review/domain/ReviewRanking.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/dto/ScoreDto.java, src/main/java/com/cheffi/review/repository/RatingJpaRepository.java, src/main/java/com/cheffi/review/repository/ViewHistoryJpaRepository.java, src/main/java/com/cheffi/review/service/RatingService.java, src/main/java/com/cheffi/review/service/ReviewSearchService.java, src/main/java/com/cheffi/review/service/ViewHistoryService.java
=> Feat: inactivate logic of locking reviews

docker-compose.yml, src/main/resources/application-dev.yml
=> Feat: use Elastic Cache instead of local `Redis` container 

src/main/java/com/cheffi/common/constant/DetailedAddress.java, src/main/java/com/cheffi/review/controller/RestaurantController.java, src/main/java/com/cheffi/review/domain/Restaurant.java, src/main/java/com/cheffi/review/domain/RestaurantData.java, src/main/java/com/cheffi/review/dto/request/QueryRestaurantRequest.java, src/main/java/com/cheffi/review/repository/RestaurantDataJpaRepository.java, src/main/java/com/cheffi/review/repository/RestaurantJpaRepository.java, src/main/java/com/cheffi/review/service/RestaurantDataService.java, src/main/java/com/cheffi/review/service/RestaurantInfoService.java, src/main/java/com/cheffi/review/service/RestaurantService.java
- 개발 DB 스키마 변경 필요
- restaurant 테이블 삭제
- coordinates 공간 인덱스 적용
- review_cnt 인덱스 적용
=> Feat: add `GET /restaurants/near` API

src/main/java/com/cheffi/avatar/controller/AvatarController.java, src/main/java/com/cheffi/avatar/dto/adapter/SelfAvatarInfo.java, src/main/java/com/cheffi/avatar/dto/common/TagDto.java, src/main/java/com/cheffi/avatar/dto/response/AddFollowResponse.java, src/main/java/com/cheffi/avatar/dto/response/AvatarInfoResponse.java, src/main/java/com/cheffi/avatar/dto/response/TagsChangeResponse.java, src/main/java/com/cheffi/avatar/dto/response/UnfollowResponse.java, src/main/java/com/cheffi/cs/dto/GetReportReasonResponse.java, src/main/java/com/cheffi/cs/dto/QnaDto.java, src/main/java/com/cheffi/oauth/dto/response/OidcLoginResponse.java, src/main/java/com/cheffi/profile/dto/MyPageInfo.java, src/main/java/com/cheffi/profile/dto/ProfileInfo.java, src/main/java/com/cheffi/region/service/RegionDto.java, src/main/java/com/cheffi/review/dto/RestaurantInfoDto.java, src/main/java/com/cheffi/review/dto/ReviewInfoDto.java, src/main/java/com/cheffi/review/dto/response/GetReviewResponse.java, src/main/java/com/cheffi/review/dto/response/ReviewWriterInfoDto.java, src/main/java/com/cheffi/user/dto/adapter/UserInfo.java
1. nullable대신 require = true 옵션사용
2. package단위로 commit message 작성
```
ex) Docs: add require option of {pakage 이름}
```
3. common response 작성하지 않음
=> Docs: add require option

src/main/java/com/cheffi/review/domain/Review.java, src/main/java/com/cheffi/review/repository/RatingJpaRepository.java, src/main/java/com/cheffi/review/repository/ReviewJpaRepository.java, src/main/java/com/cheffi/review/repository/ViewHistoryJpaRepository.java
지역별 최초 연산이 너무 오래걸리는 문제점 해결
- Related to #81
=> Feat: improve query for performance

src/main/java/com/cheffi/avatar/controller/FollowController.java, src/main/java/com/cheffi/avatar/dto/request/RecommendFollowRequest.java, src/main/java/com/cheffi/avatar/repository/FollowJpaRepository.java, src/main/java/com/cheffi/avatar/service/FollowService.java, src/main/java/com/cheffi/common/dto/ValidationGroups.java, src/main/java/com/cheffi/common/dto/ValidationSequence.java
- 여러개의 태그 ID를 파라미터로 받을 수 있도록 수정
- Validation 그룹 및 순서를 위한 클래스 추가
- https://dncjf64.tistory.com/302
=> Feat: change `GET /follows/recommend/tags` API to get multiple tag parameters
